version: '3.8'

services:
  payment-gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID:rzp_test_your_key_id_here}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET:your_secret_key_here}
    depends_on:
      - postgres
    networks:
      - payment-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - payment-network

volumes:
  postgres_data:

networks:
  payment-network:
    driver: bridge 